# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-02 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u041d\u044d\u0440')),
                ('pic', models.ImageField(blank=True, upload_to='currency/', verbose_name='\u0417\u0443\u0440\u0430\u0433')),
                ('sortname', models.CharField(max_length=200, verbose_name='\u0411\u043e\u0433\u0438\u043d\u043e \u043d\u044d\u0440')),
            ],
        ),
        migrations.CreateModel(
            name='rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rates', models.CharField(max_length=200, verbose_name='\u0425\u0430\u043d\u0448')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.currency', verbose_name='\u0412\u0430\u043b\u044e\u0442')),
            ],
        ),
    ]
