# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-11 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='rates',
        ),
        migrations.AddField(
            model_name='rate',
            name='rates_buy',
            field=models.CharField(default=0, max_length=200, verbose_name='\u0425\u0430\u043d\u0448 \u0430\u0432\u0430\u0445'),
        ),
        migrations.AddField(
            model_name='rate',
            name='rates_sell',
            field=models.CharField(default=0, max_length=200, verbose_name='\u0425\u0430\u043d\u0448 \u0437\u0430\u0440\u0430\u0445'),
        ),
    ]
